// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwdJV1ulPJ2jIrdPkXMtfNHsN4GPzT3ng',
    appId: '1:657399172326:web:c225a3708182ffcea67f27',
    messagingSenderId: '657399172326',
    projectId: 'signin-example-a3c39',
    authDomain: 'signin-example-a3c39.firebaseapp.com',
    storageBucket: 'signin-example-a3c39.appspot.com',
    measurementId: 'G-PSTSB8LX94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf-7gD33SnDx3T9D7ntY1JGcAxjXrhnaE',
    appId: '1:657399172326:android:2fdbf111b995ec55a67f27',
    messagingSenderId: '657399172326',
    projectId: 'signin-example-a3c39',
    storageBucket: 'signin-example-a3c39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpP8mRQGSJ2_IU354fgd6o1KyzKi8SspY',
    appId: '1:657399172326:ios:3353c84b3cda1241a67f27',
    messagingSenderId: '657399172326',
    projectId: 'signin-example-a3c39',
    storageBucket: 'signin-example-a3c39.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
